version: "3.9"
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3303:3306
    volumes:
      - ./embeded/lib/mysql:/var/lib/mysql
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    volumes:
      - ./embeded/lib/redis:/var/lib/redis
